name: "Shopify Theme Minifier"
description: "Minify the files of a Shopify theme"
inputs:
  themePath:
    description: "Relative path under $GITHUB_WORKSPACE where the theme root files are placed"

  ignore:
    description: "Files to be ignored (in glob format)"

  include:
    description: "Files to be included (in glob format)"

  outDir:
    description: "Output directory of minified files"

  dryRun:
    description: "Print minified files to the console instead of writing to the output files"

  sourceMap:
    description: "Control source map generation"

runs:
  using: node16
  main: dist/index.js
